name:                adventOfCode2022
version:             0.1.0.0
github:              "pepijno/adventOfCode2022"
license:             BSD3
author:              "pepijno"
copyright:           "2022 pepijno"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pepijno/adventOfCode2022#readme>

dependencies:
- base >= 4.7 && < 5
- split
- containers
- extra
- vector
- distributive
- adjunctions
- comonad
- hashable
- parsec
- array
- pqueue
- timeit
- multiset
- mtl
- unordered-containers

library:
  source-dirs: src

_exe-defs: &exe-defaults
  other-modules: []
  source-dirs: app
  dependencies:
  - adventOfCode2022
  ghc-options:
  - -O2
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  day24:
    main: Day24.hs
    <<: *exe-defaults
  day23:
    main: Day23.hs
    <<: *exe-defaults
  day22:
    main: Day22.hs
    <<: *exe-defaults
  day21:
    main: Day21.hs
    <<: *exe-defaults
  day20:
    main: Day20.hs
    <<: *exe-defaults
  day19:
    main: Day19.hs
    <<: *exe-defaults
  day18:
    main: Day18.hs
    <<: *exe-defaults
  day17:
    main: Day17.hs
    <<: *exe-defaults
  day16:
    main: Day16.hs
    <<: *exe-defaults
  day15:
    main: Day15.hs
    <<: *exe-defaults
  day14:
    main: Day14.hs
    <<: *exe-defaults
  day13:
    main: Day13.hs
    <<: *exe-defaults
  day12:
    main: Day12.hs
    <<: *exe-defaults
  day11:
    main: Day11.hs
    <<: *exe-defaults
  day10:
    main: Day10.hs
    <<: *exe-defaults
  day9:
    main: Day9.hs
    <<: *exe-defaults
  day8:
    main: Day8.hs
    <<: *exe-defaults
  day7:
    main: Day7.hs
    <<: *exe-defaults
  day6:
    main: Day6.hs
    <<: *exe-defaults
  day5:
    main: Day5.hs
    <<: *exe-defaults
  day4:
    main: Day4.hs
    <<: *exe-defaults
  day3:
    main: Day3.hs
    <<: *exe-defaults
  day2:
    main: Day2.hs
    <<: *exe-defaults
  day1:
    main: Day1.hs
    <<: *exe-defaults

tests:
  adventOfCode2022-test:
    main:                Spec.hs
    source-dirs:         test
    <<: *exe-defaults

default-extensions:
  - NumericUnderscores
  - TypeApplications
  - LambdaCase
  - FlexibleContexts
  - TupleSections
